# Generated by Django 3.1.6 on 2021-03-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
